server.port=${PORT:8081}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/circuit_simulator}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:circuitsim}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:circuitsim}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false